#!/usr/bin/env bash

currentBranch=`git branch | grep \* | cut -d ' ' -f2`
head=`git rev-parse HEAD`

git checkout -B gh-pages
git merge $currentBranch
yarn build
git add -f dist
git commit -m $head
git subtree push --prefix dist/ origin gh-pages

git chckout $currentBranch
